### ISSUE TITLE
'NoneType' object has no attribute '__dict__'`

### ISSUE THREAD

**Issue by FaiChou** [cxiaoer/NikeRobot#3]
`请输入鞋子地址:http://store.nike.com/cn/zh_cn/pd/air-jordan-31-bg-%E5%A4%A7%E7%AB%A5%E7%AF%AE%E7%90%83%E7%AB%A5%E9%9E%8B/pid-11097105/pgid-11498339
2016-12-06 11:55:49,561  MainThread  INFO  开始访问:http://store.nike.com/cn/zh_cn/pd/air-jordan-31-bg-%E5%A4%A7%E7%AB%A5%E7%AF%AE%E7%90%83%E7%AB%A5%E9%9E%8B/pid-11097105/pgid-11498339 获取商品信息.
2016-12-06 11:55:49,566  MainThread  INFO  Starting new HTTP connection (1): store.nike.com
2016-12-06 11:55:49,654  Thread-1  INFO  [第1次] 开始尝试添加到购物车了
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Users/FaiChou/Desktop/NikeRobot-master/nike_robot_new.py", line 129, in run
    add_to_cart_url, params=self.param.__dict__, headers=HEADERS)
AttributeError: 'NoneType' object has no attribute '__dict__'`

**Comment by cool403** [comment]
@FaiChou  现在应该好了
